### Criar pessoa
POST http://localhost:8080/api/pessoas
Content-Type: application/json

{"nome":"Camila Ferreira","cpf":"55566677788","email":"camila@example.com"}

### Abrir conta
POST http://localhost:8080/api/contas
Content-Type: application/json

{"agencia":"0001","numero":"200001-9","saldoInicial":250.00,"ativa":true,"titularId":1,"tipoContaId":1}

### Consultar conta
GET http://localhost:8080/api/contas/1

### Depositar
PATCH http://localhost:8080/api/contas/1/depositos
Content-Type: application/json

{"valor":100.00}

### Saque inválido
PATCH http://localhost:8080/api/contas/1/saques
Content-Type: application/json

{"valor":500.00}
