spring.datasource.url=jdbc:postgresql://localhost:5432/banco_horizonte
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.jpa.hibernate.ddl-auto=validate
spring.sql.init.mode=always
server.port=8080
