spring.application.name=banco-horizonte
server.port=${SERVER_PORT:8080}


spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/banco_horizonte}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:}

# Apenas para a aula. Em producao, use migracoes com Flyway ou Liquibase.
# spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# OpenAPI e Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha